// Find all icons at: https://antonreshetov.github.io/vue-unicons/

import Unicon from 'vue-unicons'

import {
  uniAngleDown,
  uniAppsSolid,
  uniArrowDown,
  uniArrowLeft,
  uniArrowRight,
  uniBars,
  uniCheck,
  uniCheckCircle,
  uniClipboard,
  uniCog,
  uniBug,
  uniExclamationCircle,
  uniExclamationTriangle,
  uniExternalLinkAlt,
  uniFileDownload,
  uniFileExport,
  uniFileImport,
  uniFileUpload,
  uniFilter,
  uniFilterSlash,
  uniImageSlash,
  uniInfoCircle,
  uniListUl,
  uniMobileAndroid,
  uniQuestionCircle,
  uniSave,
  uniSearch,
  uniStar,
  uniStarSolid,
  uniTimes,
  uniTrash,
} from 'vue-unicons/dist/icons'

Unicon.add([
  uniAngleDown,
  uniAppsSolid,
  uniArrowDown,
  uniArrowLeft,
  uniArrowRight,
  uniBars,
  uniCheck,
  uniCheckCircle,
  uniClipboard,
  uniCog,
  uniBug,
  uniExclamationCircle,
  uniExclamationTriangle,
  uniExternalLinkAlt,
  uniFileDownload,
  uniFileExport,
  uniFileImport,
  uniFileUpload,
  uniFilter,
  uniFilterSlash,
  uniImageSlash,
  uniInfoCircle,
  uniListUl,
  uniMobileAndroid,
  uniQuestionCircle,
  uniSave,
  uniSearch,
  uniStar,
  uniStarSolid,
  uniTimes,
  uniTrash,
])

export default Unicon
